# Generated by Django 5.0.4 on 2024-06-12 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leave", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leave",
            name="type_of_leave",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="leave.typeofleave",
                verbose_name="type de congé",
            ),
        ),
    ]
