# Dockerfile.slave for Slave Database
FROM postgres:latest

# Copy the initialization script and standby.signal file
COPY ./slave-init/init-slave.sql /docker-entrypoint-initdb.d/
COPY ./slave-init/standby.signal /tmp/standby.signal

# Ensure proper permissions for the files
RUN chown postgres:postgres /tmp/standby.signal