# Generated by Django 5.0.4 on 2024-04-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='widget',
            name='description',
        ),
        migrations.AddField(
            model_name='widget',
            name='column',
            field=models.CharField(choices=[('col-1', '1/12'), ('col-2', '2/12'), ('col-3', '3/12'), ('col-4', '4/12'), ('col-5', '5/12'), ('col-6', '6/12'), ('col-7', '7/12'), ('col-8', '8/12'), ('col-9', '9/12'), ('col-10', '10/12'), ('col-11', '11/12'), ('col-12', '12/12')], default='col-12', max_length=10, verbose_name='column'),
        ),
    ]
