# Generated by Django 5.1.3 on 2024-12-10 14:31

import core.models.fields.jsonfield
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="approval",
            name="metadata",
        ),
        migrations.RemoveField(
            model_name="contenttypeapprover",
            name="metadata",
        ),
        migrations.RemoveField(
            model_name="job",
            name="metadata",
        ),
        migrations.RemoveField(
            model_name="menu",
            name="metadata",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="metadata",
        ),
        migrations.RemoveField(
            model_name="preference",
            name="metadata",
        ),
        migrations.RemoveField(
            model_name="template",
            name="metadata",
        ),
        migrations.RemoveField(
            model_name="usercontenttypeapprover",
            name="metadata",
        ),
        migrations.RemoveField(
            model_name="widget",
            name="metadata",
        ),
        migrations.AddField(
            model_name="approval",
            name="_metadata",
            field=core.models.fields.jsonfield.JSONField(
                blank=True, default=dict, verbose_name="metadata"
            ),
        ),
        migrations.AddField(
            model_name="contenttypeapprover",
            name="_metadata",
            field=core.models.fields.jsonfield.JSONField(
                blank=True, default=dict, verbose_name="metadata"
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="_metadata",
            field=core.models.fields.jsonfield.JSONField(
                blank=True, default=dict, verbose_name="metadata"
            ),
        ),
        migrations.AddField(
            model_name="menu",
            name="_metadata",
            field=core.models.fields.jsonfield.JSONField(
                blank=True, default=dict, verbose_name="metadata"
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="_metadata",
            field=core.models.fields.jsonfield.JSONField(
                blank=True, default=dict, verbose_name="metadata"
            ),
        ),
        migrations.AddField(
            model_name="preference",
            name="_metadata",
            field=core.models.fields.jsonfield.JSONField(
                blank=True, default=dict, verbose_name="metadata"
            ),
        ),
        migrations.AddField(
            model_name="template",
            name="_metadata",
            field=core.models.fields.jsonfield.JSONField(
                blank=True, default=dict, verbose_name="metadata"
            ),
        ),
        migrations.AddField(
            model_name="usercontenttypeapprover",
            name="_metadata",
            field=core.models.fields.jsonfield.JSONField(
                blank=True, default=dict, verbose_name="metadata"
            ),
        ),
        migrations.AddField(
            model_name="widget",
            name="_metadata",
            field=core.models.fields.jsonfield.JSONField(
                blank=True, default=dict, verbose_name="metadata"
            ),
        ),
    ]
