# Generated by Django 5.1.3 on 2024-12-12 09:13

import core.models.fields.booleanfield
import core.models.fields.charfield
import core.models.fields.datetimefield
import core.models.fields.filefield
import core.models.fields.foreignkey
import core.models.fields.jsonfield
import core.models.fields.model_select_field
import core.models.fields.textfield
import core.utils.upload_directory_file
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0002_remove_approval_metadata_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Importer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "updated_at",
                    core.models.fields.datetimefield.DateTimeField(
                        auto_now=True, verbose_name="mis à jour le/à"
                    ),
                ),
                (
                    "created_at",
                    core.models.fields.datetimefield.DateTimeField(
                        auto_now_add=True, verbose_name="créé le/à"
                    ),
                ),
                (
                    "approved",
                    core.models.fields.booleanfield.BooleanField(
                        default=False, editable=False, verbose_name="approuvé"
                    ),
                ),
                (
                    "_metadata",
                    core.models.fields.jsonfield.JSONField(
                        blank=True, default=dict, verbose_name="metadata"
                    ),
                ),
                (
                    "status",
                    core.models.fields.charfield.CharField(
                        choices=[
                            ("processing", "en cours"),
                            ("pending", "en attente"),
                            ("success", "succès"),
                            ("error", "erreur"),
                        ],
                        default="pending",
                        max_length=255,
                        verbose_name="état",
                    ),
                ),
                (
                    "message",
                    core.models.fields.textfield.TextField(
                        blank=True, default=None, null=True, verbose_name="message"
                    ),
                ),
                (
                    "document",
                    core.models.fields.filefield.FileField(
                        upload_to=core.utils.upload_directory_file,
                        verbose_name="document",
                    ),
                ),
                (
                    "content_type",
                    core.models.fields.model_select_field.ModelSelectField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                        verbose_name="type de contenue",
                    ),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="créé par",
                    ),
                ),
                (
                    "organization",
                    core.models.fields.foreignkey.ForeignKey(
                        blank=True,
                        default=None,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.organization",
                        verbose_name="organisation",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        on_update=True,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="mis à jour par",
                    ),
                ),
            ],
            options={
                "verbose_name": "importateur",
                "verbose_name_plural": "importateurs",
            },
        ),
    ]
