# Generated by Django 5.0.4 on 2024-06-04 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_user_organization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importer",
            name="status",
            field=models.CharField(
                choices=[
                    ("processing", "en cours"),
                    ("pending", "en attente"),
                    ("success", "succès"),
                    ("error", "erreur"),
                ],
                default="pending",
                max_length=255,
                verbose_name="état",
            ),
        ),
    ]
