# Generated by Django 5.1.3 on 2024-12-12 10:11

import core.models.fields.charfield
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_importer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='frequency',
            field=core.models.fields.charfield.CharField(choices=[('HOURLY', 'horaire'), ('DAILY', 'quotidien'), ('WEEKLY', 'hebdomadaire'), ('MONTHLY', 'mensuel'), ('YEARLY', 'annuel')], max_length=10, verbose_name='fréquence'),
        ),
    ]
