# Generated by Django 5.1.3 on 2025-01-03 11:51

import core.models.fields.booleanfield
import core.models.fields.charfield
import core.models.fields.datetimefield
import core.models.fields.foreignkey
import core.models.fields.html_field
import core.models.fields.model_select_field
import core.models.fields.model_select_to_multiple_field
import core.models.fields.select_create_choice_field
import core.models.preference
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0020_alter_permission_content_type_alter_permission_role_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicaltemplate",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical modèle de document",
                "verbose_name_plural": "historical modèles de documents",
            },
        ),
        migrations.AlterModelOptions(
            name="importer",
            options={
                "verbose_name": "importateur",
                "verbose_name_plural": "importateurs",
            },
        ),
        migrations.AlterModelOptions(
            name="preference",
            options={
                "verbose_name": "préférence",
                "verbose_name_plural": "préférences",
            },
        ),
        migrations.AlterModelOptions(
            name="template",
            options={
                "verbose_name": "modèle de document",
                "verbose_name_plural": "modèles de documents",
            },
        ),
        migrations.AlterField(
            model_name="historicaltemplate",
            name="content",
            field=core.models.fields.html_field.HTMLField(
                default=None, null=True, verbose_name="contenu"
            ),
        ),
        migrations.AlterField(
            model_name="historicaltemplate",
            name="content_type",
            field=core.models.fields.model_select_field.ModelSelectField(
                blank=True,
                db_constraint=False,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="contenttypes.contenttype",
                verbose_name="type de contenu",
            ),
        ),
        migrations.AlterField(
            model_name="historicaltemplate",
            name="created_at",
            field=core.models.fields.datetimefield.DateTimeField(
                blank=True, editable=False, verbose_name="créé le/à"
            ),
        ),
        migrations.AlterField(
            model_name="historicaltemplate",
            name="created_by",
            field=django_currentuser.db.models.fields.CurrentUserField(
                blank=True,
                db_constraint=False,
                default=django_currentuser.middleware.get_current_authenticated_user,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="créé par",
            ),
        ),
        migrations.AlterField(
            model_name="historicaltemplate",
            name="name",
            field=core.models.fields.charfield.CharField(
                db_index=True, max_length=100, verbose_name="nom"
            ),
        ),
        migrations.AlterField(
            model_name="historicaltemplate",
            name="organization",
            field=core.models.fields.foreignkey.ForeignKey(
                blank=True,
                db_constraint=False,
                default=None,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.organization",
                verbose_name="organisation",
            ),
        ),
        migrations.AlterField(
            model_name="historicaltemplate",
            name="updated_at",
            field=core.models.fields.datetimefield.DateTimeField(
                blank=True, editable=False, verbose_name="mis à jour le/à"
            ),
        ),
        migrations.AlterField(
            model_name="historicaltemplate",
            name="updated_by",
            field=django_currentuser.db.models.fields.CurrentUserField(
                db_constraint=False,
                default=django_currentuser.middleware.get_current_authenticated_user,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                on_update=True,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="mis à jour par",
            ),
        ),
        migrations.AlterField(
            model_name="historicaluser",
            name="created_at",
            field=core.models.fields.datetimefield.DateTimeField(
                blank=True, editable=False, verbose_name="créé le/à"
            ),
        ),
        migrations.AlterField(
            model_name="historicaluser",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Précise si l’utilisateur doit être considéré comme actif. Décochez ceci plutôt que de supprimer le compte.",
                verbose_name="actif",
            ),
        ),
        migrations.AlterField(
            model_name="historicaluser",
            name="is_staff",
            field=core.models.fields.booleanfield.BooleanField(
                default=False,
                help_text="Précise si l’utilisateur peut se connecter à ce site d'administration.",
                verbose_name="statut équipe",
            ),
        ),
        migrations.AlterField(
            model_name="historicaluser",
            name="organization",
            field=core.models.fields.model_select_field.ModelSelectField(
                blank=True,
                db_constraint=False,
                default=None,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.organization",
                verbose_name="organisation",
            ),
        ),
        migrations.AlterField(
            model_name="historicaluser",
            name="password",
            field=core.models.fields.charfield.CharField(
                blank=True, max_length=128, verbose_name="mot de passe"
            ),
        ),
        migrations.AlterField(
            model_name="historicaluser",
            name="updated_at",
            field=core.models.fields.datetimefield.DateTimeField(
                blank=True, editable=False, verbose_name="mis à jour le/à"
            ),
        ),
        migrations.AlterField(
            model_name="historicalwidget",
            name="content_type",
            field=core.models.fields.model_select_field.ModelSelectField(
                blank=True,
                db_constraint=False,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="contenttypes.contenttype",
                verbose_name="type de contenu",
            ),
        ),
        migrations.AlterField(
            model_name="historicalwidget",
            name="created_at",
            field=core.models.fields.datetimefield.DateTimeField(
                blank=True, editable=False, verbose_name="créé le/à"
            ),
        ),
        migrations.AlterField(
            model_name="historicalwidget",
            name="created_by",
            field=django_currentuser.db.models.fields.CurrentUserField(
                blank=True,
                db_constraint=False,
                default=django_currentuser.middleware.get_current_authenticated_user,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="créé par",
            ),
        ),
        migrations.AlterField(
            model_name="historicalwidget",
            name="name",
            field=models.CharField(max_length=100, verbose_name="nom"),
        ),
        migrations.AlterField(
            model_name="historicalwidget",
            name="organization",
            field=core.models.fields.foreignkey.ForeignKey(
                blank=True,
                db_constraint=False,
                default=None,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.organization",
                verbose_name="organisation",
            ),
        ),
        migrations.AlterField(
            model_name="historicalwidget",
            name="updated_at",
            field=core.models.fields.datetimefield.DateTimeField(
                blank=True, editable=False, verbose_name="mis à jour le/à"
            ),
        ),
        migrations.AlterField(
            model_name="historicalwidget",
            name="updated_by",
            field=django_currentuser.db.models.fields.CurrentUserField(
                db_constraint=False,
                default=django_currentuser.middleware.get_current_authenticated_user,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                on_update=True,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="mis à jour par",
            ),
        ),
        migrations.AlterField(
            model_name="importer",
            name="content_type",
            field=core.models.fields.foreignkey.ForeignKey(
                default=None,
                limit_choices_to={
                    "app_label__in": ["core"],
                    "model__in": ["preference", "widget"],
                },
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contenttypes.contenttype",
                verbose_name="type de contenu",
            ),
        ),
        migrations.AlterField(
            model_name="importer",
            name="created_at",
            field=core.models.fields.datetimefield.DateTimeField(
                auto_now_add=True, verbose_name="créé le/à"
            ),
        ),
        migrations.AlterField(
            model_name="importer",
            name="created_by",
            field=django_currentuser.db.models.fields.CurrentUserField(
                default=django_currentuser.middleware.get_current_authenticated_user,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="créé par",
            ),
        ),
        migrations.AlterField(
            model_name="importer",
            name="organization",
            field=core.models.fields.foreignkey.ForeignKey(
                blank=True,
                default=None,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.organization",
                verbose_name="organisation",
            ),
        ),
        migrations.AlterField(
            model_name="importer",
            name="status",
            field=core.models.fields.charfield.CharField(
                choices=[
                    ("processing", "en cours"),
                    ("pending", "en attente"),
                    ("success", "succès"),
                    ("error", "erreur"),
                ],
                default="pending",
                max_length=255,
                verbose_name="état",
            ),
        ),
        migrations.AlterField(
            model_name="importer",
            name="updated_at",
            field=core.models.fields.datetimefield.DateTimeField(
                auto_now=True, verbose_name="mis à jour le/à"
            ),
        ),
        migrations.AlterField(
            model_name="importer",
            name="updated_by",
            field=django_currentuser.db.models.fields.CurrentUserField(
                default=django_currentuser.middleware.get_current_authenticated_user,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                on_update=True,
                related_name="%(app_label)s_%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="mis à jour par",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="created_at",
            field=core.models.fields.datetimefield.DateTimeField(
                auto_now_add=True, verbose_name="créé le/à"
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="created_by",
            field=django_currentuser.db.models.fields.CurrentUserField(
                default=django_currentuser.middleware.get_current_authenticated_user,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="créé par",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="frequency",
            field=core.models.fields.charfield.CharField(
                choices=[
                    ("HOURLY", "horaire"),
                    ("DAILY", "quotidien"),
                    ("WEEKLY", "hebdomadaire"),
                    ("MONTHLY", "mensuel"),
                    ("YEARLY", "annuel"),
                ],
                max_length=10,
                verbose_name="fréquence",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="name",
            field=core.models.fields.charfield.CharField(
                max_length=255, verbose_name="nom"
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="organization",
            field=core.models.fields.foreignkey.ForeignKey(
                blank=True,
                default=None,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.organization",
                verbose_name="organisation",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="updated_at",
            field=core.models.fields.datetimefield.DateTimeField(
                auto_now=True, verbose_name="mis à jour le/à"
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="updated_by",
            field=django_currentuser.db.models.fields.CurrentUserField(
                default=django_currentuser.middleware.get_current_authenticated_user,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                on_update=True,
                related_name="%(app_label)s_%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="mis à jour par",
            ),
        ),
        migrations.AlterField(
            model_name="menu",
            name="children",
            field=core.models.fields.model_select_to_multiple_field.ModelSelect2Multiple(
                to="contenttypes.contenttype", verbose_name="sous-menu"
            ),
        ),
        migrations.AlterField(
            model_name="menu",
            name="created_at",
            field=core.models.fields.datetimefield.DateTimeField(
                auto_now_add=True, verbose_name="créé le/à"
            ),
        ),
        migrations.AlterField(
            model_name="menu",
            name="created_by",
            field=django_currentuser.db.models.fields.CurrentUserField(
                default=django_currentuser.middleware.get_current_authenticated_user,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="créé par",
            ),
        ),
        migrations.AlterField(
            model_name="menu",
            name="name",
            field=core.models.fields.charfield.CharField(
                max_length=100, unique=True, verbose_name="nom"
            ),
        ),
        migrations.AlterField(
            model_name="menu",
            name="organization",
            field=core.models.fields.foreignkey.ForeignKey(
                blank=True,
                default=None,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.organization",
                verbose_name="organisation",
            ),
        ),
        migrations.AlterField(
            model_name="menu",
            name="updated_at",
            field=core.models.fields.datetimefield.DateTimeField(
                auto_now=True, verbose_name="mis à jour le/à"
            ),
        ),
        migrations.AlterField(
            model_name="menu",
            name="updated_by",
            field=django_currentuser.db.models.fields.CurrentUserField(
                default=django_currentuser.middleware.get_current_authenticated_user,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                on_update=True,
                related_name="%(app_label)s_%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="mis à jour par",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="_from",
            field=core.models.fields.model_select_field.ModelSelectField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_notifications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="de",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="_to",
            field=core.models.fields.model_select_field.ModelSelectField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="à",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="created_at",
            field=core.models.fields.datetimefield.DateTimeField(
                auto_now_add=True, verbose_name="créé le/à"
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="created_by",
            field=django_currentuser.db.models.fields.CurrentUserField(
                default=django_currentuser.middleware.get_current_authenticated_user,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="créé par",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="organization",
            field=core.models.fields.foreignkey.ForeignKey(
                blank=True,
                default=None,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.organization",
                verbose_name="organisation",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="redirect",
            field=core.models.fields.charfield.CharField(
                blank=True, max_length=255, null=True, verbose_name="rediriger vers"
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="subject",
            field=core.models.fields.charfield.CharField(
                max_length=255, verbose_name="sujet"
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="updated_at",
            field=core.models.fields.datetimefield.DateTimeField(
                auto_now=True, verbose_name="mis à jour le/à"
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="updated_by",
            field=django_currentuser.db.models.fields.CurrentUserField(
                default=django_currentuser.middleware.get_current_authenticated_user,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                on_update=True,
                related_name="%(app_label)s_%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="mis à jour par",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="viewed",
            field=core.models.fields.booleanfield.BooleanField(
                default=False, verbose_name="vu"
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="created_at",
            field=core.models.fields.datetimefield.DateTimeField(
                auto_now_add=True, verbose_name="créé le/à"
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="created_by",
            field=django_currentuser.db.models.fields.CurrentUserField(
                default=django_currentuser.middleware.get_current_authenticated_user,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="créé par",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="name",
            field=core.models.fields.charfield.CharField(
                max_length=100, verbose_name="nom"
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="updated_at",
            field=core.models.fields.datetimefield.DateTimeField(
                auto_now=True, verbose_name="mis à jour le/à"
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="updated_by",
            field=django_currentuser.db.models.fields.CurrentUserField(
                default=django_currentuser.middleware.get_current_authenticated_user,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                on_update=True,
                related_name="%(app_label)s_%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="mis à jour par",
            ),
        ),
        migrations.AlterField(
            model_name="permission",
            name="content_type",
            field=core.models.fields.foreignkey.ForeignKey(
                default=None,
                limit_choices_to={"app_label__in": ["core", "employee", "payroll"]},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="permissions",
                to="contenttypes.contenttype",
                verbose_name="type de contenu",
            ),
        ),
        migrations.AlterField(
            model_name="permission",
            name="created_at",
            field=core.models.fields.datetimefield.DateTimeField(
                auto_now_add=True, verbose_name="créé le/à"
            ),
        ),
        migrations.AlterField(
            model_name="permission",
            name="organization",
            field=core.models.fields.foreignkey.ForeignKey(
                blank=True,
                default=None,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.organization",
                verbose_name="organisation",
            ),
        ),
        migrations.AlterField(
            model_name="permission",
            name="role",
            field=core.models.fields.model_select_field.ModelSelectField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="permissions",
                to="core.role",
                verbose_name="rôle",
            ),
        ),
        migrations.AlterField(
            model_name="permission",
            name="updated_at",
            field=core.models.fields.datetimefield.DateTimeField(
                auto_now=True, verbose_name="mis à jour le/à"
            ),
        ),
        migrations.AlterField(
            model_name="permission",
            name="user",
            field=core.models.fields.model_select_field.ModelSelectField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="permissions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="utilisateur",
            ),
        ),
        migrations.AlterField(
            model_name="permission",
            name="view",
            field=core.models.fields.booleanfield.BooleanField(
                default=False, verbose_name="voir"
            ),
        ),
        migrations.AlterField(
            model_name="preference",
            name="created_at",
            field=core.models.fields.datetimefield.DateTimeField(
                auto_now_add=True, verbose_name="créé le/à"
            ),
        ),
        migrations.AlterField(
            model_name="preference",
            name="created_by",
            field=django_currentuser.db.models.fields.CurrentUserField(
                default=django_currentuser.middleware.get_current_authenticated_user,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="créé par",
            ),
        ),
        migrations.AlterField(
            model_name="preference",
            name="key",
            field=core.models.fields.select_create_choice_field.SelectCreateChoiceField(
                choices=core.models.preference.preferences,
                max_length=100,
                unique=True,
                verbose_name="clé",
            ),
        ),
        migrations.AlterField(
            model_name="preference",
            name="organization",
            field=core.models.fields.foreignkey.ForeignKey(
                blank=True,
                default=None,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.organization",
                verbose_name="organisation",
            ),
        ),
        migrations.AlterField(
            model_name="preference",
            name="updated_at",
            field=core.models.fields.datetimefield.DateTimeField(
                auto_now=True, verbose_name="mis à jour le/à"
            ),
        ),
        migrations.AlterField(
            model_name="preference",
            name="updated_by",
            field=django_currentuser.db.models.fields.CurrentUserField(
                default=django_currentuser.middleware.get_current_authenticated_user,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                on_update=True,
                related_name="%(app_label)s_%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="mis à jour par",
            ),
        ),
        migrations.AlterField(
            model_name="preference",
            name="value",
            field=core.models.fields.charfield.CharField(
                max_length=100, verbose_name="valeur"
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="created_at",
            field=core.models.fields.datetimefield.DateTimeField(
                auto_now_add=True, verbose_name="créé le/à"
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="created_by",
            field=django_currentuser.db.models.fields.CurrentUserField(
                default=django_currentuser.middleware.get_current_authenticated_user,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="créé par",
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="name",
            field=core.models.fields.charfield.CharField(
                max_length=255, unique=True, verbose_name="nom"
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="organization",
            field=core.models.fields.foreignkey.ForeignKey(
                blank=True,
                default=None,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.organization",
                verbose_name="organisation",
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="updated_at",
            field=core.models.fields.datetimefield.DateTimeField(
                auto_now=True, verbose_name="mis à jour le/à"
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="updated_by",
            field=django_currentuser.db.models.fields.CurrentUserField(
                default=django_currentuser.middleware.get_current_authenticated_user,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                on_update=True,
                related_name="%(app_label)s_%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="mis à jour par",
            ),
        ),
        migrations.AlterField(
            model_name="rowlevelsecurity",
            name="content_type",
            field=core.models.fields.foreignkey.ForeignKey(
                default=None,
                limit_choices_to={"app_label__in": ["core", "employee", "payroll"]},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rows",
                to="contenttypes.contenttype",
                verbose_name="type de contenu",
            ),
        ),
        migrations.AlterField(
            model_name="rowlevelsecurity",
            name="created_at",
            field=core.models.fields.datetimefield.DateTimeField(
                auto_now_add=True, verbose_name="créé le/à"
            ),
        ),
        migrations.AlterField(
            model_name="rowlevelsecurity",
            name="organization",
            field=core.models.fields.foreignkey.ForeignKey(
                blank=True,
                default=None,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.organization",
                verbose_name="organisation",
            ),
        ),
        migrations.AlterField(
            model_name="rowlevelsecurity",
            name="role",
            field=core.models.fields.model_select_field.ModelSelectField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rows",
                to="core.role",
                verbose_name="rôle",
            ),
        ),
        migrations.AlterField(
            model_name="rowlevelsecurity",
            name="updated_at",
            field=core.models.fields.datetimefield.DateTimeField(
                auto_now=True, verbose_name="mis à jour le/à"
            ),
        ),
        migrations.AlterField(
            model_name="rowlevelsecurity",
            name="user",
            field=core.models.fields.model_select_field.ModelSelectField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rows",
                to=settings.AUTH_USER_MODEL,
                verbose_name="utilisateur",
            ),
        ),
        migrations.AlterField(
            model_name="rowlevelsecurity",
            name="value",
            field=core.models.fields.charfield.CharField(
                max_length=255, verbose_name="valeur"
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="content",
            field=core.models.fields.html_field.HTMLField(
                default=None, null=True, verbose_name="contenu"
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="content_type",
            field=core.models.fields.model_select_field.ModelSelectField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
                verbose_name="type de contenu",
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="created_at",
            field=core.models.fields.datetimefield.DateTimeField(
                auto_now_add=True, verbose_name="créé le/à"
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="created_by",
            field=django_currentuser.db.models.fields.CurrentUserField(
                default=django_currentuser.middleware.get_current_authenticated_user,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="créé par",
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="name",
            field=core.models.fields.charfield.CharField(
                max_length=100, unique=True, verbose_name="nom"
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="organization",
            field=core.models.fields.foreignkey.ForeignKey(
                blank=True,
                default=None,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.organization",
                verbose_name="organisation",
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="updated_at",
            field=core.models.fields.datetimefield.DateTimeField(
                auto_now=True, verbose_name="mis à jour le/à"
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="updated_by",
            field=django_currentuser.db.models.fields.CurrentUserField(
                default=django_currentuser.middleware.get_current_authenticated_user,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                on_update=True,
                related_name="%(app_label)s_%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="mis à jour par",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=core.models.fields.datetimefield.DateTimeField(
                auto_now_add=True, verbose_name="créé le/à"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Précise si l’utilisateur doit être considéré comme actif. Décochez ceci plutôt que de supprimer le compte.",
                verbose_name="actif",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=core.models.fields.booleanfield.BooleanField(
                default=False,
                help_text="Précise si l’utilisateur peut se connecter à ce site d'administration.",
                verbose_name="statut équipe",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="organization",
            field=core.models.fields.model_select_field.ModelSelectField(
                blank=True,
                default=None,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.organization",
                verbose_name="organisation",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=core.models.fields.charfield.CharField(
                blank=True, max_length=128, verbose_name="mot de passe"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_at",
            field=core.models.fields.datetimefield.DateTimeField(
                auto_now=True, verbose_name="mis à jour le/à"
            ),
        ),
        migrations.AlterField(
            model_name="widget",
            name="content_type",
            field=core.models.fields.model_select_field.ModelSelectField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contenttypes.contenttype",
                verbose_name="type de contenu",
            ),
        ),
        migrations.AlterField(
            model_name="widget",
            name="created_at",
            field=core.models.fields.datetimefield.DateTimeField(
                auto_now_add=True, verbose_name="créé le/à"
            ),
        ),
        migrations.AlterField(
            model_name="widget",
            name="created_by",
            field=django_currentuser.db.models.fields.CurrentUserField(
                default=django_currentuser.middleware.get_current_authenticated_user,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="créé par",
            ),
        ),
        migrations.AlterField(
            model_name="widget",
            name="name",
            field=models.CharField(max_length=100, verbose_name="nom"),
        ),
        migrations.AlterField(
            model_name="widget",
            name="organization",
            field=core.models.fields.foreignkey.ForeignKey(
                blank=True,
                default=None,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.organization",
                verbose_name="organisation",
            ),
        ),
        migrations.AlterField(
            model_name="widget",
            name="updated_at",
            field=core.models.fields.datetimefield.DateTimeField(
                auto_now=True, verbose_name="mis à jour le/à"
            ),
        ),
        migrations.AlterField(
            model_name="widget",
            name="updated_by",
            field=django_currentuser.db.models.fields.CurrentUserField(
                default=django_currentuser.middleware.get_current_authenticated_user,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                on_update=True,
                related_name="%(app_label)s_%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="mis à jour par",
            ),
        ),
    ]
