# Generated by Django 5.0.4 on 2024-05-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="grade",
            name="category",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="catégorie"
            ),
        ),
    ]
