# Generated by Django 5.0.4 on 2024-09-21 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="position",
            name="working_days_per_month",
            field=models.IntegerField(
                default=30, verbose_name="jours de travail par mois"
            ),
        ),
    ]
