# Generated by Django 5.0.4 on 2024-04-25 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employee",
            options={
                "ordering": ("registration_number",),
                "verbose_name": "employé",
                "verbose_name_plural": "employés",
            },
        ),
    ]
