# Generated by Django 5.1.3 on 2024-12-13 05:48

import core.models.fields.emailfield
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="email",
            field=core.models.fields.emailfield.EmailField(
                blank=True,
                default=None,
                max_length=254,
                null=True,
                verbose_name="email",
            ),
        ),
    ]
