# Generated by Django 5.0.4 on 2024-05-28 12:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("employee", "0002_grade_category"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Designation",
            new_name="Position",
        ),
        migrations.RenameField(
            model_name="employee",
            old_name="designation",
            new_name="position",
        ),
    ]
