# Generated by Django 5.0.4 on 2024-09-21 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0002_position_working_days_per_month"),
    ]

    operations = [
        #migrations.RemoveField(
        #    model_name="interim",
        #    name="created_by",
        #),
        #migrations.RemoveField(
        #    model_name="interim",
        #    name="employee",
        #),
        #migrations.RemoveField(
        #    model_name="interim",
        #    name="grade",
        #),
        #migrations.RemoveField(
        #    model_name="interim",
        #    name="organization",
        #),
        #migrations.RemoveField(
        #    model_name="interim",
        #    name="updated_by",
        #),
        migrations.DeleteModel(
            name="Commission",
        ),
        migrations.DeleteModel(
            name="Interim",
        ),
    ]
