# Generated by Django 5.0.4 on 2024-05-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0003_rename_designation_position_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="position",
            name="name",
            field=models.CharField(max_length=100, verbose_name="nom"),
        ),
    ]
