# Generated by Django 5.0.4 on 2024-09-24 06:06

import core.models.fields.json_field
import employee.models.employee
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0003_remove_interim_created_by_remove_interim_employee_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="is_housed",
            field=models.BooleanField(
                default=False,
                help_text="L'employé est-il logé par l'organisation ?",
                verbose_name="logé",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="metadata",
            field=core.models.fields.json_field.JSONField(
                blank=True,
                default=employee.models.employee._metadata,
                verbose_name="meta",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="mileage_allowance",
            field=models.BooleanField(
                default=0,
                help_text="L'employé bénéficie-t-il de l'indemnité kilométrique ?",
                verbose_name="indemnité kilométrique",
            ),
        ),
    ]
