# Generated by Django 5.0.4 on 2024-09-24 09:33

import core.models.fields.date_field
import core.models.fields.model_select_field
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0004_alter_employee_is_housed_alter_employee_metadata_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="direction",
            options={
                "verbose_name": "departement",
                "verbose_name_plural": "departements",
            },
        ),
        migrations.AddField(
            model_name="employee",
            name="date_of_leave",
            field=core.models.fields.date_field.DateField(
                default=None, null=True, verbose_name="date de fin de service"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="direction",
            field=core.models.fields.model_select_field.ModelSelect(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="employee.direction",
                verbose_name="departement",
            ),
        ),
    ]
