# Generated by Django 5.0.4 on 2024-05-28 12:58

import core.models.fields.model_select_field
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0004_alter_position_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="iterim",
            field=core.models.fields.model_select_field.ModelSelect(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="iterim_employee",
                to="employee.grade",
                verbose_name="iterim",
            ),
        ),
    ]
