# Generated by Django 5.0.4 on 2024-05-28 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0005_employee_iterim"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="father_name",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=100,
                null=True,
                verbose_name="nom du père",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="mother_name",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=100,
                null=True,
                verbose_name="nom de la mère",
            ),
        ),
    ]
