# Generated by Django 5.0.4 on 2024-09-24 09:44

import core.models.fields.date_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0005_alter_direction_options_employee_date_of_leave_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="date_of_leave",
            field=core.models.fields.date_field.DateField(
                blank=True,
                default=None,
                null=True,
                verbose_name="date de fin de service",
            ),
        ),
    ]
