# Generated by Django 5.0.4 on 2024-05-28 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0006_employee_father_name_employee_mother_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employee",
            options={
                "ordering": ("-registration_number",),
                "verbose_name": "employé",
                "verbose_name_plural": "employés",
            },
        ),
        migrations.RemoveField(
            model_name="employee",
            name="father_name",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="mother_name",
        ),
    ]
