# Generated by Django 5.0.4 on 2024-06-02 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "employee",
            "0007_alter_employee_options_remove_employee_father_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employee",
            options={
                "ordering": ("-status", "registration_number"),
                "verbose_name": "employé",
                "verbose_name_plural": "employés",
            },
        ),
    ]
