# Generated by Django 5.0.4 on 2024-06-04 17:49

import core.models.fields.model_select_field
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0008_alter_employee_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="status",
            options={"verbose_name": "état", "verbose_name_plural": "état"},
        ),
        migrations.AlterField(
            model_name="employee",
            name="status",
            field=core.models.fields.model_select_field.ModelSelect(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="employee.status",
                verbose_name="état",
            ),
        ),
    ]
