# Generated by Django 5.0.4 on 2024-06-12 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0009_alter_status_options_alter_employee_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="education",
            options={"verbose_name": "étude", "verbose_name_plural": "études"},
        ),
        migrations.AlterModelOptions(
            name="payer",
            options={"verbose_name": "banque", "verbose_name_plural": "banques"},
        ),
        migrations.AlterModelOptions(
            name="position",
            options={"verbose_name": "poste", "verbose_name_plural": "postes"},
        ),
        migrations.AddField(
            model_name="payer",
            name="code",
            field=models.CharField(
                default=None, max_length=10, null=True, verbose_name="code"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="physical_address",
            field=models.TextField(
                default=None, null=True, verbose_name="adresse physique"
            ),
        ),
    ]
