# Generated by Django 5.0.4 on 2024-07-08 16:10

import core.models.fields.model_select_field
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0010_alter_education_options_alter_payer_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="branch",
            options={"verbose_name": "zone", "verbose_name_plural": "zones"},
        ),
        migrations.AlterModelOptions(
            name="status",
            options={
                "verbose_name": "code activité",
                "verbose_name_plural": "code activités",
            },
        ),
        migrations.AlterField(
            model_name="employee",
            name="gender",
            field=models.CharField(
                choices=[("male", "Homme"), ("female", "Femme")],
                max_length=10,
                verbose_name="genre",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="marital_status",
            field=models.CharField(
                choices=[
                    ("maried", "Marié"),
                    ("widower", "Veuf"),
                    ("single", "Célibataire"),
                ],
                max_length=12,
                verbose_name="état civil",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="payer_name",
            field=core.models.fields.model_select_field.ModelSelect(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="employee.payer",
                verbose_name="banque",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("bank", "Bank"),
                    ("mobile Money", "Mobile Money"),
                ],
                max_length=20,
                verbose_name="mode de paiement",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="status",
            field=core.models.fields.model_select_field.ModelSelect(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="employee.status",
                verbose_name="code d'activité",
            ),
        ),
    ]
