# Generated by Django 5.0.4 on 2024-07-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0011_alter_branch_options_alter_status_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="status",
            name="category",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="catégorie"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="marital_status",
            field=models.CharField(
                choices=[
                    ("married", "Marié"),
                    ("widower", "Veuf"),
                    ("single", "Célibataire"),
                ],
                max_length=12,
                verbose_name="état civil",
            ),
        ),
    ]
