# Generated by Django 5.0.4 on 2024-07-09 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0012_status_category_alter_employee_marital_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payer",
            name="code",
        ),
        migrations.AddField(
            model_name="payer",
            name="category",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="catégorie"
            ),
        ),
    ]
