# Generated by Django 5.0.4 on 2024-07-09 15:08

import core.models.fields.model_select_field
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0013_remove_payer_code_payer_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="iterim",
        ),
        migrations.AlterField(
            model_name="employee",
            name="agreement",
            field=core.models.fields.model_select_field.ModelSelect(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="employee.agreement",
                verbose_name="type de contrat",
            ),
        ),
    ]
