# Generated by Django 5.0.4 on 2024-07-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0015_rename_payer_name_employee_payer"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="category",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="catégorie"
            ),
        ),
    ]
