# Generated by Django 5.0.4 on 2024-04-25 13:01

import core.models.fields.ace_field
import core.models.fields.date_field
import core.models.fields.json_field
import core.models.fields.model_select_to_multiple_field
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("employee", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DutyItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="mis à jour le/à"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le/à"),
                ),
                (
                    "metadata",
                    core.models.fields.json_field.JSONField(
                        blank=True, default=dict, verbose_name="meta"
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=100, unique=True, verbose_name="code"),
                ),
                (
                    "type_of_item",
                    models.IntegerField(
                        choices=[(1, "Remunerative"), (-1, "Deductible")],
                        default=1,
                        verbose_name="type d'element",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="nom")),
                (
                    "time",
                    core.models.fields.ace_field.AceField(
                        default="0", verbose_name="temps"
                    ),
                ),
                (
                    "condition",
                    core.models.fields.ace_field.AceField(
                        default="0", verbose_name="condition"
                    ),
                ),
                (
                    "formula",
                    core.models.fields.ace_field.AceField(
                        default="0", verbose_name="formule/montant"
                    ),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="créé par",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.organization",
                        verbose_name="organisation",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        on_update=True,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="mis à jour par",
                    ),
                ),
            ],
            options={
                "verbose_name": "autre element",
                "verbose_name_plural": "autre elements",
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="mis à jour le/à"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le/à"),
                ),
                (
                    "metadata",
                    core.models.fields.json_field.JSONField(
                        blank=True, default=dict, verbose_name="meta"
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=100, unique=True, verbose_name="code"),
                ),
                (
                    "type_of_item",
                    models.IntegerField(
                        choices=[(1, "Remunerative"), (-1, "Deductible")],
                        default=1,
                        verbose_name="type d'element",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="nom")),
                (
                    "time",
                    core.models.fields.ace_field.AceField(
                        default="0", verbose_name="temps"
                    ),
                ),
                (
                    "formula",
                    core.models.fields.ace_field.AceField(
                        default="0", verbose_name="forumule/montant"
                    ),
                ),
                (
                    "condition",
                    core.models.fields.ace_field.AceField(
                        default="0", verbose_name="condition"
                    ),
                ),
                (
                    "is_payable",
                    models.BooleanField(
                        default=True,
                        help_text="Cet élément est payable",
                        verbose_name="est payable",
                    ),
                ),
                (
                    "is_taxable",
                    models.BooleanField(
                        default=False,
                        help_text="Cet élément fera partie du montant brut imposable",
                        verbose_name="is impossable",
                    ),
                ),
                (
                    "is_social_security",
                    models.BooleanField(
                        default=False,
                        help_text="Cet élément fera partie du seuil de sécurité sociale",
                        verbose_name="est éligible à la sécurité sociale",
                    ),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="créé par",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.organization",
                        verbose_name="organisation",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        on_update=True,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="mis à jour par",
                    ),
                ),
            ],
            options={
                "verbose_name": "element de paie",
                "verbose_name_plural": "elements de paie",
            },
        ),
        migrations.CreateModel(
            name="Payroll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="mis à jour le/à"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le/à"),
                ),
                (
                    "metadata",
                    core.models.fields.json_field.JSONField(
                        blank=True, default=dict, verbose_name="meta"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="nom")),
                (
                    "start_dt",
                    core.models.fields.date_field.DateField(verbose_name="du"),
                ),
                ("end_dt", core.models.fields.date_field.DateField(verbose_name="au")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "succès"),
                            ("WARNING", "avertissement"),
                            ("PROGRESS", "en cours"),
                        ],
                        default="PROGRESS",
                        editable=False,
                        max_length=25,
                        verbose_name="status",
                    ),
                ),
                (
                    "overall_net",
                    models.FloatField(
                        blank=True, default=0, editable=False, verbose_name="net global"
                    ),
                ),
                (
                    "branch",
                    core.models.fields.model_select_to_multiple_field.ModelSelect2Multiple(
                        blank=True,
                        help_text="laisser vide pour tous",
                        to="employee.branch",
                        verbose_name="site",
                    ),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="créé par",
                    ),
                ),
                (
                    "direction",
                    core.models.fields.model_select_to_multiple_field.ModelSelect2Multiple(
                        blank=True,
                        help_text="laisser vide pour tous",
                        to="employee.direction",
                        verbose_name="direction",
                    ),
                ),
                (
                    "grade",
                    core.models.fields.model_select_to_multiple_field.ModelSelect2Multiple(
                        blank=True,
                        help_text="laisser vide pour tous",
                        to="employee.grade",
                        verbose_name="grade",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.organization",
                        verbose_name="organisation",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        on_update=True,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="mis à jour par",
                    ),
                ),
            ],
            options={
                "verbose_name": "paie",
                "verbose_name_plural": "paies",
            },
        ),
        migrations.CreateModel(
            name="Payslip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="mis à jour le/à"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le/à"),
                ),
                (
                    "metadata",
                    core.models.fields.json_field.JSONField(
                        blank=True, default=dict, verbose_name="meta"
                    ),
                ),
                (
                    "social_security_threshold",
                    models.FloatField(default=0, verbose_name="plafond cnss/cnsap"),
                ),
                (
                    "taxable_gross",
                    models.FloatField(default=0, verbose_name="brut imposable"),
                ),
                ("gross", models.FloatField(default=0, verbose_name="brut")),
                ("net", models.FloatField(default=0, verbose_name="net")),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="créé par",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employee.employee",
                        verbose_name="employé",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.organization",
                        verbose_name="organisation",
                    ),
                ),
                (
                    "payroll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payroll.payroll",
                        verbose_name="paie",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        on_update=True,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="mis à jour par",
                    ),
                ),
            ],
            options={
                "verbose_name": "fiche de paie",
                "verbose_name_plural": "fiches de paie",
            },
        ),
        migrations.CreateModel(
            name="PayItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="mis à jour le/à"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le/à"),
                ),
                (
                    "metadata",
                    core.models.fields.json_field.JSONField(
                        blank=True, default=dict, verbose_name="meta"
                    ),
                ),
                (
                    "type_of_item",
                    models.IntegerField(
                        choices=[(1, "remunerative"), (-1, "deductible")],
                        default=1,
                        verbose_name="type d'element",
                    ),
                ),
                ("code", models.CharField(max_length=100, verbose_name="code")),
                ("name", models.CharField(max_length=100, verbose_name="nom")),
                ("time", models.FloatField(default=0, verbose_name="temps")),
                ("rate", models.FloatField(default=0, verbose_name="taux")),
                ("amount", models.FloatField(default=0, verbose_name="montant")),
                (
                    "taxable_amount",
                    models.FloatField(default=0, verbose_name="montant imposable"),
                ),
                (
                    "social_security_amount",
                    models.FloatField(
                        default=0, verbose_name="plafond de la sécurité sociale"
                    ),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="créé par",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.organization",
                        verbose_name="organisation",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        on_update=True,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="mis à jour par",
                    ),
                ),
                (
                    "payslip",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payroll.payslip",
                        verbose_name="fiche de paie",
                    ),
                ),
            ],
            options={
                "verbose_name": "element payé",
                "verbose_name_plural": "elements payé",
            },
        ),
    ]
