# Generated by Django 5.1.3 on 2024-12-12 15:11

import core.models.fields.floatfield
import core.models.fields.jsonfield
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payroll",
            name="metadata",
        ),
        migrations.AddField(
            model_name="payroll",
            name="_metadata",
            field=core.models.fields.jsonfield.JSONField(
                blank=True, default=dict, verbose_name="metadata"
            ),
        ),
        migrations.AlterField(
            model_name="specialemployeeitem",
            name="amount_qp_employee",
            field=core.models.fields.floatfield.FloatField(
                blank=True,
                default=None,
                help_text="laisser vide pour utiliser la formule de l'element",
                null=True,
                verbose_name="montant qp employé",
            ),
        ),
        migrations.AlterField(
            model_name="specialemployeeitem",
            name="amount_qp_employer",
            field=core.models.fields.floatfield.FloatField(
                blank=True,
                default=None,
                help_text="laisser vide pour utiliser la formule de l'element",
                null=True,
                verbose_name="montant qp employeur",
            ),
        ),
    ]
