# Generated by Django 5.0.4 on 2024-04-25 18:49

import core.models.fields.ace_field
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_importer_status"),
        ("payroll", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PayItem",
            new_name="ItemPaie",
        ),
        migrations.AlterModelOptions(
            name="dutyitem",
            options={
                "verbose_name": "éléments légaux de la paie",
                "verbose_name_plural": "éléments légaux de la paies",
            },
        ),
        migrations.RemoveField(
            model_name="dutyitem",
            name="formula",
        ),
        migrations.RemoveField(
            model_name="dutyitem",
            name="time",
        ),
        migrations.AddField(
            model_name="dutyitem",
            name="formula_qp_employee",
            field=core.models.fields.ace_field.AceField(
                default="0", verbose_name="formule/montant quote part employee"
            ),
        ),
        migrations.AddField(
            model_name="dutyitem",
            name="formula_qp_employer",
            field=core.models.fields.ace_field.AceField(
                default="0", verbose_name="formule/montant quote part employeur"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="is_taxable",
            field=models.BooleanField(
                default=False,
                help_text="Cet élément fera partie du montant brut imposable",
                verbose_name="est impossable",
            ),
        ),
    ]
