# Generated by Django 5.0.4 on 2024-07-10 13:21

import core.models.fields.date_field
import core.models.fields.json_field
import core.models.fields.model_select_field
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_menu_icon"),
        ("employee", "0014_remove_employee_iterim_alter_employee_agreement"),
        ("payroll", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="mis à jour le/à"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le/à"),
                ),
                (
                    "metadata",
                    core.models.fields.json_field.JSONField(
                        blank=True, default=dict, verbose_name="meta"
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(max_length=50, verbose_name="matricule"),
                ),
                (
                    "social_security_number",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=50,
                        null=True,
                        verbose_name="numéro de sécurité sociale",
                    ),
                ),
                (
                    "date_of_join",
                    core.models.fields.date_field.DateField(
                        default=None, null=True, verbose_name="date d'engagement"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="", verbose_name="photo"
                    ),
                ),
                (
                    "middle_name",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=100,
                        null=True,
                        verbose_name="post-nom",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=100,
                        null=True,
                        verbose_name="prénom",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=100,
                        null=True,
                        verbose_name="nom",
                    ),
                ),
                (
                    "date_of_birth",
                    core.models.fields.date_field.DateField(
                        default=None, null=True, verbose_name="date de naissance"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Homme"), ("female", "Femme")],
                        max_length=10,
                        verbose_name="genre",
                    ),
                ),
                (
                    "marital_status",
                    models.CharField(
                        choices=[
                            ("married", "Marié"),
                            ("widower", "Veuf"),
                            ("single", "Célibataire"),
                        ],
                        max_length=12,
                        verbose_name="état civil",
                    ),
                ),
                (
                    "spouse",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=100,
                        null=True,
                        verbose_name="conjoint",
                    ),
                ),
                (
                    "mobile_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        default=None,
                        max_length=128,
                        null=True,
                        region=None,
                        verbose_name="numéro de téléphone mobile",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        default=None,
                        max_length=254,
                        null=True,
                        verbose_name="email",
                    ),
                ),
                (
                    "physical_address",
                    models.TextField(
                        default=None, null=True, verbose_name="adresse physique"
                    ),
                ),
                (
                    "emergency_information",
                    models.TextField(
                        default=None, null=True, verbose_name="informations d'urgence"
                    ),
                ),
                (
                    "payment_account",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=50,
                        null=True,
                        verbose_name="numéro de compte",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("bank", "Bank"),
                            ("mobile Money", "Mobile Money"),
                        ],
                        max_length=20,
                        verbose_name="mode de paiement",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, default=None, null=True, verbose_name="commentaire"
                    ),
                ),
                (
                    "agreement",
                    core.models.fields.model_select_field.ModelSelect(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_agreement",
                        to="employee.agreement",
                        verbose_name="type de contrat",
                    ),
                ),
                (
                    "branch",
                    core.models.fields.model_select_field.ModelSelect(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_branch",
                        to="employee.branch",
                        verbose_name="site",
                    ),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="créé par",
                    ),
                ),
                (
                    "direction",
                    core.models.fields.model_select_field.ModelSelect(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_direction",
                        to="employee.direction",
                        verbose_name="direction",
                    ),
                ),
                (
                    "grade",
                    core.models.fields.model_select_field.ModelSelect(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_grade",
                        to="employee.grade",
                        verbose_name="grade",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_organization",
                        to="core.organization",
                        verbose_name="organisation",
                    ),
                ),
                (
                    "payer_name",
                    core.models.fields.model_select_field.ModelSelect(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_payer_name",
                        to="employee.payer",
                        verbose_name="banque",
                    ),
                ),
                (
                    "payroll",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payroll.payroll",
                        verbose_name="paie",
                    ),
                ),
                (
                    "service",
                    core.models.fields.model_select_field.ModelSelect(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_service",
                        to="employee.service",
                        verbose_name="service",
                    ),
                ),
                (
                    "status",
                    core.models.fields.model_select_field.ModelSelect(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_status",
                        to="employee.status",
                        verbose_name="code d'activité",
                    ),
                ),
                (
                    "sub_direction",
                    core.models.fields.model_select_field.ModelSelect(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_sub_direction",
                        to="employee.subdirection",
                        verbose_name="sous-direction",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        on_update=True,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="mis à jour par",
                    ),
                ),
            ],
            options={
                "verbose_name": "employé",
                "verbose_name_plural": "employés",
                "ordering": ("-status", "registration_number"),
            },
        ),
    ]
