# Generated by Django 5.0.4 on 2024-06-02 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payslip",
            name="employee",
            field=models.JSONField(default=dict, verbose_name="employé"),
        ),
    ]
