# Generated by Django 5.0.4 on 2024-04-25 18:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_importer_status"),
        ("payroll", "0002_rename_payitem_itempaie_alter_dutyitem_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DutyItem",
            new_name="LegalItem",
        ),
    ]
