# Generated by Django 5.0.4 on 2024-06-02 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0008_alter_employee_options"),
        ("payroll", "0002_alter_payslip_employee"),
    ]

    operations = [
        migrations.AddField(
            model_name="payslip",
            name="_employee",
            field=models.JSONField(default=dict, verbose_name="employé"),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="employee",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="employee.employee",
                verbose_name="employé",
            ),
        ),
    ]
