# Generated by Django 5.0.4 on 2024-09-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0002_claim"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="specialemployeeitem",
            name="condition",
        ),
        migrations.AddField(
            model_name="specialemployeeitem",
            name="amount_qp_employee",
            field=models.FloatField(
                blank=True,
                default=None,
                help_text="laisser vide pour utiliser la formule de l'element",
                null=True,
                verbose_name="montant qp employé",
            ),
        ),
    ]
