# Generated by Django 5.0.4 on 2024-07-10 13:22

import core.models.fields.model_select_field
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0014_remove_employee_iterim_alter_employee_agreement"),
        ("payroll", "0002_employee"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="position",
            field=core.models.fields.model_select_field.ModelSelect(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_position",
                to="employee.position",
                verbose_name="position",
            ),
        ),
    ]
