# Generated by Django 5.0.4 on 2024-04-25 19:01

import core.models.fields.ace_field
import core.models.fields.json_field
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_importer_status"),
        ("payroll", "0003_rename_dutyitem_legalitem"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="formula",
        ),
        migrations.AddField(
            model_name="item",
            name="formula_qp_employee",
            field=core.models.fields.ace_field.AceField(
                default="0", verbose_name="formule/montant quote part employee"
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="formula_qp_employer",
            field=core.models.fields.ace_field.AceField(
                default="0", verbose_name="formule/montant quote part employeur"
            ),
        ),
        migrations.AlterField(
            model_name="legalitem",
            name="type_of_item",
            field=models.IntegerField(
                choices=[(1, "Remunerative"), (-1, "Deductible")],
                default=-1,
                verbose_name="type d'element",
            ),
        ),
        migrations.CreateModel(
            name="ItemPaid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="mis à jour le/à"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le/à"),
                ),
                (
                    "metadata",
                    core.models.fields.json_field.JSONField(
                        blank=True, default=dict, verbose_name="meta"
                    ),
                ),
                (
                    "type_of_item",
                    models.IntegerField(
                        choices=[(1, "remunerative"), (-1, "deductible")],
                        default=1,
                        verbose_name="type d'element",
                    ),
                ),
                ("code", models.CharField(max_length=100, verbose_name="code")),
                ("name", models.CharField(max_length=100, verbose_name="nom")),
                ("time", models.FloatField(default=0, verbose_name="temps")),
                ("rate", models.FloatField(default=0, verbose_name="taux")),
                (
                    "amount_qp_employer",
                    models.FloatField(
                        default=0, verbose_name="montant quote part employeur"
                    ),
                ),
                (
                    "amount_qp_employee",
                    models.FloatField(
                        default=0, verbose_name="montant quote part employee"
                    ),
                ),
                (
                    "social_security_amount",
                    models.FloatField(
                        default=0, verbose_name="plafond de la sécurité sociale"
                    ),
                ),
                (
                    "taxable_amount",
                    models.FloatField(default=0, verbose_name="montant imposable"),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="créé par",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.organization",
                        verbose_name="organisation",
                    ),
                ),
                (
                    "payslip",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payroll.payslip",
                        verbose_name="fiche de paie",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        on_update=True,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="mis à jour par",
                    ),
                ),
            ],
            options={
                "verbose_name": "element payé",
                "verbose_name_plural": "elements payé",
            },
        ),
        migrations.DeleteModel(
            name="ItemPaie",
        ),
    ]
