# Generated by Django 5.0.4 on 2024-06-02 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0003_payslip__employee_alter_payslip_employee"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payslip",
            name="_employee",
        ),
        migrations.AlterField(
            model_name="payslip",
            name="employee",
            field=models.JSONField(default=dict, verbose_name="employé"),
        ),
    ]
