# Generated by Django 5.0.4 on 2024-07-10 13:55

import core.models.fields.model_select_field
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0003_employee_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="payslip",
            name="employee",
            field=core.models.fields.model_select_field.ModelSelect(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="payroll.employee",
                verbose_name="employé",
            ),
        ),
    ]
