# Generated by Django 5.1.3 on 2024-12-13 05:57

import core.models.fields.datefield
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0003_alter_advancesalarypayment_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="specialemployeeitem",
            name="end_date",
            field=core.models.fields.datefield.DateField(
                blank=True,
                default=None,
                help_text="laisser vide pour une date illimitée",
                null=True,
                verbose_name="date de fin",
            ),
        ),
    ]
