# Generated by Django 5.0.4 on 2024-09-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0003_remove_specialemployeeitem_condition_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="specialemployeeitem",
            name="amount_qp_employer",
            field=models.FloatField(
                blank=True,
                default=None,
                help_text="laisser vide pour utiliser la formule de l'element",
                null=True,
                verbose_name="montant qp employeur",
            ),
        ),
    ]
