# Generated by Django 5.0.4 on 2024-09-23 15:52

import core.models.fields.model_select_to_multiple_field
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0004_specialemployeeitem_amount_qp_employer"),
    ]

    operations = [
        migrations.AddField(
            model_name="claim",
            name="payrolls",
            field=core.models.fields.model_select_to_multiple_field.ModelSelect2Multiple(
                to="payroll.payroll", verbose_name="paies"
            ),
        ),
        migrations.AlterField(
            model_name="claim",
            name="solved",
            field=models.BooleanField(
                help_text="coche si le problème a été résolu",
                verbose_name="Est résolu ?",
            ),
        ),
    ]
