# Generated by Django 5.0.4 on 2024-04-25 19:25

import core.models.fields.model_select_to_multiple_field
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0002_alter_employee_options"),
        ("payroll", "0004_remove_item_formula_item_formula_qp_employee_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payroll",
            old_name="branch",
            new_name="employee_branch",
        ),
        migrations.RenameField(
            model_name="payroll",
            old_name="direction",
            new_name="employee_direction",
        ),
        migrations.RenameField(
            model_name="payroll",
            old_name="grade",
            new_name="employee_grade",
        ),
        migrations.AddField(
            model_name="payroll",
            name="employee_status",
            field=core.models.fields.model_select_to_multiple_field.ModelSelect2Multiple(
                blank=True,
                help_text="laisser vide pour tous",
                to="employee.status",
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="status",
            field=models.CharField(
                choices=[
                    ("WARNING", "avertissement"),
                    ("PROGRESS", "en cours"),
                    ("SUCCESS", "succès"),
                ],
                default="PROGRESS",
                editable=False,
                max_length=25,
                verbose_name="status",
            ),
        ),
    ]
