# Generated by Django 5.0.4 on 2024-07-10 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0015_rename_payer_name_employee_payer"),
        ("payroll", "0004_payslip_employee"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employee",
            old_name="payer_name",
            new_name="payer",
        ),
    ]
