# Generated by Django 5.1.3 on 2024-12-27 09:30

import core.models.fields.ace_field
import core.models.fields.charfield
import core.models.fields.datefield
import core.models.fields.datetimefield
import core.models.fields.floatfield
import core.models.fields.foreignkey
import core.models.fields.model_select_field
import core.models.fields.model_select_to_multiple_field
import core.models.fields.textfield
import core.utils.upload_directory_file
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_contenttypeapprover_content_type_and_more"),
        ("employee", "0003_alter_agreement_options_alter_child_options_and_more"),
        ("payroll", "0004_specialemployeeitem_end_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="advancesalary",
            options={
                "verbose_name": "salary advance",
                "verbose_name_plural": "salary advances",
            },
        ),
        migrations.AlterModelOptions(
            name="advancesalarypayment",
            options={
                "verbose_name": "salary advance payment",
                "verbose_name_plural": "salary advance payments",
            },
        ),
        migrations.AlterModelOptions(
            name="item",
            options={
                "verbose_name": "payroll element",
                "verbose_name_plural": "payroll elements",
            },
        ),
        migrations.AlterModelOptions(
            name="itempaid",
            options={
                "verbose_name": "paid element",
                "verbose_name_plural": "paid elements",
            },
        ),
        migrations.AlterModelOptions(
            name="legalitem",
            options={
                "verbose_name": "Legal withholding",
                "verbose_name_plural": "Legal withholdings",
            },
        ),
        migrations.AlterModelOptions(
            name="paidemployee",
            options={
                "ordering": ("-status", "registration_number"),
                "verbose_name": "paid employee",
                "verbose_name_plural": "paid employees",
            },
        ),
        migrations.AlterModelOptions(
            name="payroll",
            options={"verbose_name": "payroll", "verbose_name_plural": "payrolls"},
        ),
        migrations.AlterModelOptions(
            name="payslip",
            options={"verbose_name": "payslip", "verbose_name_plural": "payslips"},
        ),
        migrations.AlterModelOptions(
            name="specialemployeeitem",
            options={
                "verbose_name": "special element for the employee",
                "verbose_name_plural": "special element for the employee",
            },
        ),
        migrations.RemoveField(
            model_name="advancesalary",
            name="approved",
        ),
        migrations.RemoveField(
            model_name="advancesalarypayment",
            name="approved",
        ),
        migrations.RemoveField(
            model_name="item",
            name="approved",
        ),
        migrations.RemoveField(
            model_name="itempaid",
            name="approved",
        ),
        migrations.RemoveField(
            model_name="legalitem",
            name="approved",
        ),
        migrations.RemoveField(
            model_name="paidemployee",
            name="approved",
        ),
        migrations.RemoveField(
            model_name="specialemployeeitem",
            name="approved",
        ),
        migrations.AlterField(
            model_name="advancesalary",
            name="amount",
            field=models.FloatField(verbose_name="amount"),
        ),
        migrations.AlterField(
            model_name="advancesalary",
            name="created_at",
            field=core.models.fields.datetimefield.DateTimeField(
                auto_now_add=True, verbose_name="created at"
            ),
        ),
        migrations.AlterField(
            model_name="advancesalary",
            name="created_by",
            field=django_currentuser.db.models.fields.CurrentUserField(
                default=django_currentuser.middleware.get_current_authenticated_user,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="created by",
            ),
        ),
        migrations.AlterField(
            model_name="advancesalary",
            name="duration",
            field=models.IntegerField(
                default=36, help_text="number of months", verbose_name="duration"
            ),
        ),
        migrations.AlterField(
            model_name="advancesalary",
            name="employee",
            field=core.models.fields.model_select_field.ModelSelectField(
                on_delete=django.db.models.deletion.CASCADE,
                to="employee.employee",
                verbose_name="employee",
            ),
        ),
        migrations.AlterField(
            model_name="advancesalary",
            name="organization",
            field=core.models.fields.foreignkey.ForeignKey(
                blank=True,
                default=None,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.organization",
                verbose_name="organization",
            ),
        ),
        migrations.AlterField(
            model_name="advancesalary",
            name="updated_at",
            field=core.models.fields.datetimefield.DateTimeField(
                auto_now=True, verbose_name="updated at"
            ),
        ),
        migrations.AlterField(
            model_name="advancesalary",
            name="updated_by",
            field=django_currentuser.db.models.fields.CurrentUserField(
                default=django_currentuser.middleware.get_current_authenticated_user,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                on_update=True,
                related_name="%(app_label)s_%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="updated by",
            ),
        ),
        migrations.AlterField(
            model_name="advancesalarypayment",
            name="advance_salary",
            field=core.models.fields.model_select_field.ModelSelectField(
                on_delete=django.db.models.deletion.CASCADE,
                to="payroll.advancesalary",
                verbose_name="salary advance",
            ),
        ),
        migrations.AlterField(
            model_name="advancesalarypayment",
            name="amount",
            field=core.models.fields.floatfield.FloatField(verbose_name="amount"),
        ),
        migrations.AlterField(
            model_name="advancesalarypayment",
            name="created_at",
            field=core.models.fields.datetimefield.DateTimeField(
                auto_now_add=True, verbose_name="created at"
            ),
        ),
        migrations.AlterField(
            model_name="advancesalarypayment",
            name="created_by",
            field=django_currentuser.db.models.fields.CurrentUserField(
                default=django_currentuser.middleware.get_current_authenticated_user,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="created by",
            ),
        ),
        migrations.AlterField(
            model_name="advancesalarypayment",
            name="organization",
            field=core.models.fields.foreignkey.ForeignKey(
                blank=True,
                default=None,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.organization",
                verbose_name="organization",
            ),
        ),
        migrations.AlterField(
            model_name="advancesalarypayment",
            name="updated_at",
            field=core.models.fields.datetimefield.DateTimeField(
                auto_now=True, verbose_name="updated at"
            ),
        ),
        migrations.AlterField(
            model_name="advancesalarypayment",
            name="updated_by",
            field=django_currentuser.db.models.fields.CurrentUserField(
                default=django_currentuser.middleware.get_current_authenticated_user,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                on_update=True,
                related_name="%(app_label)s_%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="updated by",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="created_at",
            field=core.models.fields.datetimefield.DateTimeField(
                auto_now_add=True, verbose_name="created at"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="created_by",
            field=django_currentuser.db.models.fields.CurrentUserField(
                default=django_currentuser.middleware.get_current_authenticated_user,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="created by",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="formula_qp_employee",
            field=core.models.fields.ace_field.AceField(
                default="0",
                help_text='press "Ctrl+Space" to get code completion',
                verbose_name="formula/amount employee share",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="formula_qp_employer",
            field=core.models.fields.ace_field.AceField(
                default="0",
                help_text='press "Ctrl+Space" to get code completion',
                verbose_name="formula/amount employer share",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="is_bonus",
            field=models.BooleanField(
                default=False,
                help_text="This element is a bonus",
                verbose_name="is a bonus",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="is_payable",
            field=models.BooleanField(
                default=True,
                help_text="This element is payable",
                verbose_name="is payable",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="is_social_security",
            field=models.BooleanField(
                default=False,
                help_text="This element will be part of the social security threshold",
                verbose_name="is eligible for social security",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="is_taxable",
            field=models.BooleanField(
                default=False,
                help_text="This element will be part of the gross taxable amount",
                verbose_name="is taxable",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="name",
            field=models.CharField(max_length=100, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="item",
            name="organization",
            field=core.models.fields.foreignkey.ForeignKey(
                blank=True,
                default=None,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.organization",
                verbose_name="organization",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="time",
            field=core.models.fields.ace_field.AceField(
                default="0",
                help_text='press "Ctrl+Space" to get code completion',
                verbose_name="time",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="type_of_item",
            field=models.IntegerField(
                choices=[(1, "Remunerative"), (-1, "Deductible")],
                default=1,
                verbose_name="element type",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="updated_at",
            field=core.models.fields.datetimefield.DateTimeField(
                auto_now=True, verbose_name="updated at"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="updated_by",
            field=django_currentuser.db.models.fields.CurrentUserField(
                default=django_currentuser.middleware.get_current_authenticated_user,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                on_update=True,
                related_name="%(app_label)s_%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="updated by",
            ),
        ),
        migrations.AlterField(
            model_name="itempaid",
            name="amount_qp_employee",
            field=models.FloatField(default=0, verbose_name="employee share amount"),
        ),
        migrations.AlterField(
            model_name="itempaid",
            name="amount_qp_employer",
            field=models.FloatField(default=0, verbose_name="employer share amount"),
        ),
        migrations.AlterField(
            model_name="itempaid",
            name="created_at",
            field=core.models.fields.datetimefield.DateTimeField(
                auto_now_add=True, verbose_name="created at"
            ),
        ),
        migrations.AlterField(
            model_name="itempaid",
            name="created_by",
            field=django_currentuser.db.models.fields.CurrentUserField(
                default=django_currentuser.middleware.get_current_authenticated_user,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="created by",
            ),
        ),
        migrations.AlterField(
            model_name="itempaid",
            name="is_bonus",
            field=models.BooleanField(
                default=False,
                help_text="This element is a bonus",
                verbose_name="is a bonus",
            ),
        ),
        migrations.AlterField(
            model_name="itempaid",
            name="is_payable",
            field=models.BooleanField(
                default=True,
                help_text="This element is payable",
                verbose_name="is payable",
            ),
        ),
        migrations.AlterField(
            model_name="itempaid",
            name="name",
            field=models.CharField(max_length=100, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="itempaid",
            name="organization",
            field=core.models.fields.foreignkey.ForeignKey(
                blank=True,
                default=None,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.organization",
                verbose_name="organization",
            ),
        ),
        migrations.AlterField(
            model_name="itempaid",
            name="payslip",
            field=core.models.fields.model_select_field.ModelSelectField(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="payroll.payslip",
                verbose_name="payslip",
            ),
        ),
        migrations.AlterField(
            model_name="itempaid",
            name="rate",
            field=models.FloatField(default=0, verbose_name="rate"),
        ),
        migrations.AlterField(
            model_name="itempaid",
            name="social_security_amount",
            field=models.FloatField(default=0, verbose_name="social security ceiling"),
        ),
        migrations.AlterField(
            model_name="itempaid",
            name="taxable_amount",
            field=models.FloatField(default=0, verbose_name="taxable amount"),
        ),
        migrations.AlterField(
            model_name="itempaid",
            name="time",
            field=models.FloatField(default=0, verbose_name="time"),
        ),
        migrations.AlterField(
            model_name="itempaid",
            name="type_of_item",
            field=models.IntegerField(
                choices=[(1, "remunerative"), (-1, "deductible")],
                default=1,
                verbose_name="element type",
            ),
        ),
        migrations.AlterField(
            model_name="itempaid",
            name="updated_at",
            field=core.models.fields.datetimefield.DateTimeField(
                auto_now=True, verbose_name="updated at"
            ),
        ),
        migrations.AlterField(
            model_name="itempaid",
            name="updated_by",
            field=django_currentuser.db.models.fields.CurrentUserField(
                default=django_currentuser.middleware.get_current_authenticated_user,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                on_update=True,
                related_name="%(app_label)s_%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="updated by",
            ),
        ),
        migrations.AlterField(
            model_name="legalitem",
            name="created_at",
            field=core.models.fields.datetimefield.DateTimeField(
                auto_now_add=True, verbose_name="created at"
            ),
        ),
        migrations.AlterField(
            model_name="legalitem",
            name="created_by",
            field=django_currentuser.db.models.fields.CurrentUserField(
                default=django_currentuser.middleware.get_current_authenticated_user,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="created by",
            ),
        ),
        migrations.AlterField(
            model_name="legalitem",
            name="formula_qp_employee",
            field=core.models.fields.ace_field.AceField(
                default="0",
                help_text='press "Ctrl+Space" to get code completion',
                verbose_name="formula/amount employee share",
            ),
        ),
        migrations.AlterField(
            model_name="legalitem",
            name="formula_qp_employer",
            field=core.models.fields.ace_field.AceField(
                default="0",
                help_text='press "Ctrl+Space" to get code completion',
                verbose_name="formula/amount employer share",
            ),
        ),
        migrations.AlterField(
            model_name="legalitem",
            name="name",
            field=models.CharField(max_length=100, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="legalitem",
            name="organization",
            field=core.models.fields.foreignkey.ForeignKey(
                blank=True,
                default=None,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.organization",
                verbose_name="organization",
            ),
        ),
        migrations.AlterField(
            model_name="legalitem",
            name="type_of_item",
            field=models.IntegerField(
                choices=[(1, "Remunerative"), (-1, "Deductible")],
                default=-1,
                verbose_name="element type",
            ),
        ),
        migrations.AlterField(
            model_name="legalitem",
            name="updated_at",
            field=core.models.fields.datetimefield.DateTimeField(
                auto_now=True, verbose_name="updated at"
            ),
        ),
        migrations.AlterField(
            model_name="legalitem",
            name="updated_by",
            field=django_currentuser.db.models.fields.CurrentUserField(
                default=django_currentuser.middleware.get_current_authenticated_user,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                on_update=True,
                related_name="%(app_label)s_%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="updated by",
            ),
        ),
        migrations.AlterField(
            model_name="paidemployee",
            name="agreement",
            field=core.models.fields.model_select_field.ModelSelectField(
                on_delete=django.db.models.deletion.CASCADE,
                to="employee.agreement",
                verbose_name="contract type",
            ),
        ),
        migrations.AlterField(
            model_name="paidemployee",
            name="comment",
            field=core.models.fields.textfield.TextField(
                blank=True, default=None, null=True, verbose_name="comment"
            ),
        ),
        migrations.AlterField(
            model_name="paidemployee",
            name="created_at",
            field=core.models.fields.datetimefield.DateTimeField(
                auto_now_add=True, verbose_name="created at"
            ),
        ),
        migrations.AlterField(
            model_name="paidemployee",
            name="created_by",
            field=django_currentuser.db.models.fields.CurrentUserField(
                default=django_currentuser.middleware.get_current_authenticated_user,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="created by",
            ),
        ),
        migrations.AlterField(
            model_name="paidemployee",
            name="date_of_birth",
            field=core.models.fields.datefield.DateField(
                default=None,
                help_text="YYYY-MM-DD",
                null=True,
                verbose_name="date of birth",
            ),
        ),
        migrations.AlterField(
            model_name="paidemployee",
            name="date_of_join",
            field=core.models.fields.datefield.DateField(
                default=None,
                help_text="YYYY-MM-DD",
                null=True,
                verbose_name="hire date",
            ),
        ),
        migrations.AlterField(
            model_name="paidemployee",
            name="direction",
            field=core.models.fields.model_select_field.ModelSelectField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="employee.direction",
                verbose_name="department",
            ),
        ),
        migrations.AlterField(
            model_name="paidemployee",
            name="emergency_information",
            field=core.models.fields.textfield.TextField(
                default=None, null=True, verbose_name="emergency information"
            ),
        ),
        migrations.AlterField(
            model_name="paidemployee",
            name="first_name",
            field=core.models.fields.charfield.CharField(
                blank=True,
                default=None,
                max_length=100,
                null=True,
                verbose_name="first name",
            ),
        ),
        migrations.AlterField(
            model_name="paidemployee",
            name="gender",
            field=core.models.fields.charfield.CharField(
                choices=[("male", "male"), ("female", "female")],
                max_length=10,
                verbose_name="gender",
            ),
        ),
        migrations.AlterField(
            model_name="paidemployee",
            name="last_name",
            field=core.models.fields.charfield.CharField(
                blank=True, default=None, max_length=100, null=True, verbose_name="name"
            ),
        ),
        migrations.AlterField(
            model_name="paidemployee",
            name="marital_status",
            field=core.models.fields.charfield.CharField(
                choices=[
                    ("maried", "married"),
                    ("single", "single"),
                    ("widower", "widowed"),
                ],
                max_length=12,
                verbose_name="marital status",
            ),
        ),
        migrations.AlterField(
            model_name="paidemployee",
            name="middle_name",
            field=core.models.fields.charfield.CharField(
                blank=True,
                default=None,
                max_length=100,
                null=True,
                verbose_name="surname",
            ),
        ),
        migrations.AlterField(
            model_name="paidemployee",
            name="mobile_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default=None,
                max_length=128,
                null=True,
                region=None,
                verbose_name="mobile phone number",
            ),
        ),
        migrations.AlterField(
            model_name="paidemployee",
            name="organization",
            field=core.models.fields.foreignkey.ForeignKey(
                blank=True,
                default=None,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.organization",
                verbose_name="organization",
            ),
        ),
        migrations.AlterField(
            model_name="paidemployee",
            name="payer_name",
            field=core.models.fields.charfield.CharField(
                default=None, max_length=50, null=True, verbose_name="payer's name"
            ),
        ),
        migrations.AlterField(
            model_name="paidemployee",
            name="payment_account",
            field=core.models.fields.charfield.CharField(
                blank=True,
                default=None,
                max_length=50,
                null=True,
                verbose_name="account/payment number",
            ),
        ),
        migrations.AlterField(
            model_name="paidemployee",
            name="payment_method",
            field=core.models.fields.charfield.CharField(
                choices=[
                    ("cash", "cash"),
                    ("bank", "bank"),
                    ("mobile Money", "mobile Money"),
                ],
                max_length=20,
                verbose_name="payment method",
            ),
        ),
        migrations.AlterField(
            model_name="paidemployee",
            name="payroll",
            field=core.models.fields.model_select_field.ModelSelectField(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="payroll.payroll",
                verbose_name="payroll",
            ),
        ),
        migrations.AlterField(
            model_name="paidemployee",
            name="physical_address",
            field=core.models.fields.textfield.TextField(
                blank=True, default=None, null=True, verbose_name="physical address"
            ),
        ),
        migrations.AlterField(
            model_name="paidemployee",
            name="registration_number",
            field=core.models.fields.charfield.CharField(
                max_length=50, verbose_name="registration number"
            ),
        ),
        migrations.AlterField(
            model_name="paidemployee",
            name="social_security_number",
            field=core.models.fields.charfield.CharField(
                blank=True,
                default=None,
                max_length=50,
                null=True,
                verbose_name="social security number",
            ),
        ),
        migrations.AlterField(
            model_name="paidemployee",
            name="spouse",
            field=core.models.fields.charfield.CharField(
                blank=True,
                default=None,
                max_length=100,
                null=True,
                verbose_name="spouse",
            ),
        ),
        migrations.AlterField(
            model_name="paidemployee",
            name="spouse_date_of_birth",
            field=core.models.fields.datefield.DateField(
                blank=True,
                default=None,
                help_text="YYYY-MM-DD",
                null=True,
                verbose_name="spouse's date of birth",
            ),
        ),
        migrations.AlterField(
            model_name="paidemployee",
            name="status",
            field=core.models.fields.model_select_field.ModelSelectField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="employee.status",
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="paidemployee",
            name="sub_direction",
            field=core.models.fields.model_select_field.ModelSelectField(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="employee.subdirection",
                verbose_name="sub-division",
            ),
        ),
        migrations.AlterField(
            model_name="paidemployee",
            name="updated_at",
            field=core.models.fields.datetimefield.DateTimeField(
                auto_now=True, verbose_name="updated at"
            ),
        ),
        migrations.AlterField(
            model_name="paidemployee",
            name="updated_by",
            field=django_currentuser.db.models.fields.CurrentUserField(
                default=django_currentuser.middleware.get_current_authenticated_user,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                on_update=True,
                related_name="%(app_label)s_%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="updated by",
            ),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="additional_items",
            field=models.FileField(
                blank=True,
                default=None,
                null=True,
                upload_to=core.utils.upload_directory_file,
                verbose_name="additional elements",
            ),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="approved",
            field=models.BooleanField(default=False, verbose_name="approved"),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="approvers",
            field=core.models.fields.model_select_to_multiple_field.ModelSelect2Multiple(
                to=settings.AUTH_USER_MODEL, verbose_name="approvers"
            ),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="canvas",
            field=models.FileField(
                blank=True,
                default=None,
                null=True,
                upload_to=core.utils.upload_directory_file,
                verbose_name="template",
            ),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="created_at",
            field=core.models.fields.datetimefield.DateTimeField(
                auto_now_add=True, verbose_name="created at"
            ),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="created_by",
            field=django_currentuser.db.models.fields.CurrentUserField(
                default=django_currentuser.middleware.get_current_authenticated_user,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="created by",
            ),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="employee_branch",
            field=core.models.fields.model_select_to_multiple_field.ModelSelect2Multiple(
                blank=True,
                help_text="leave blank for all",
                to="employee.branch",
                verbose_name="site",
            ),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="employee_direction",
            field=core.models.fields.model_select_to_multiple_field.ModelSelect2Multiple(
                blank=True,
                help_text="leave blank for all",
                to="employee.direction",
                verbose_name="department",
            ),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="employee_grade",
            field=core.models.fields.model_select_to_multiple_field.ModelSelect2Multiple(
                blank=True,
                help_text="leave blank for all",
                to="employee.grade",
                verbose_name="grade",
            ),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="employee_status",
            field=core.models.fields.model_select_to_multiple_field.ModelSelect2Multiple(
                blank=True,
                help_text="leave blank for all",
                to="employee.status",
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="end_dt",
            field=core.models.fields.datefield.DateField(verbose_name="to"),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="name",
            field=models.CharField(max_length=100, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="organization",
            field=core.models.fields.foreignkey.ForeignKey(
                blank=True,
                default=None,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.organization",
                verbose_name="organization",
            ),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="overall_net",
            field=models.FloatField(
                blank=True, default=0, editable=False, verbose_name="total net"
            ),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="start_dt",
            field=core.models.fields.datefield.DateField(verbose_name="from"),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="status",
            field=models.CharField(
                choices=[
                    ("WARNING", "warning"),
                    ("PROGRESS", "in progress"),
                    ("SUCCESS", "success"),
                ],
                default="PROGRESS",
                editable=False,
                max_length=25,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="updated_at",
            field=core.models.fields.datetimefield.DateTimeField(
                auto_now=True, verbose_name="updated at"
            ),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="updated_by",
            field=django_currentuser.db.models.fields.CurrentUserField(
                default=django_currentuser.middleware.get_current_authenticated_user,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                on_update=True,
                related_name="%(app_label)s_%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="updated by",
            ),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="created_at",
            field=core.models.fields.datetimefield.DateTimeField(
                auto_now_add=True, verbose_name="created at"
            ),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="created_by",
            field=django_currentuser.db.models.fields.CurrentUserField(
                default=django_currentuser.middleware.get_current_authenticated_user,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="created by",
            ),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="employee",
            field=core.models.fields.model_select_field.ModelSelectField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="payroll.paidemployee",
                verbose_name="employee",
            ),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="gross",
            field=models.FloatField(default=0, verbose_name="gross"),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="organization",
            field=core.models.fields.foreignkey.ForeignKey(
                blank=True,
                default=None,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.organization",
                verbose_name="organization",
            ),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="payroll",
            field=core.models.fields.model_select_field.ModelSelectField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="payroll.payroll",
                verbose_name="payroll",
            ),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="social_security_threshold",
            field=models.FloatField(default=0, verbose_name="cnss/cnsap ceiling"),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="taxable_gross",
            field=models.FloatField(default=0, verbose_name="taxable gross"),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="updated_at",
            field=core.models.fields.datetimefield.DateTimeField(
                auto_now=True, verbose_name="updated at"
            ),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="updated_by",
            field=django_currentuser.db.models.fields.CurrentUserField(
                default=django_currentuser.middleware.get_current_authenticated_user,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                on_update=True,
                related_name="%(app_label)s_%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="updated by",
            ),
        ),
        migrations.AlterField(
            model_name="specialemployeeitem",
            name="amount_qp_employee",
            field=core.models.fields.floatfield.FloatField(
                blank=True,
                default=None,
                help_text="leave blank to use the element formula",
                null=True,
                verbose_name="employee share amount",
            ),
        ),
        migrations.AlterField(
            model_name="specialemployeeitem",
            name="amount_qp_employer",
            field=core.models.fields.floatfield.FloatField(
                blank=True,
                default=None,
                help_text="leave blank to use the element formula",
                null=True,
                verbose_name="employer share amount",
            ),
        ),
        migrations.AlterField(
            model_name="specialemployeeitem",
            name="created_at",
            field=core.models.fields.datetimefield.DateTimeField(
                auto_now_add=True, verbose_name="created at"
            ),
        ),
        migrations.AlterField(
            model_name="specialemployeeitem",
            name="created_by",
            field=django_currentuser.db.models.fields.CurrentUserField(
                default=django_currentuser.middleware.get_current_authenticated_user,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="created by",
            ),
        ),
        migrations.AlterField(
            model_name="specialemployeeitem",
            name="end_date",
            field=core.models.fields.datefield.DateField(
                blank=True,
                default=None,
                help_text="leave blank for unlimited date",
                null=True,
                verbose_name="end date",
            ),
        ),
        migrations.AlterField(
            model_name="specialemployeeitem",
            name="item",
            field=core.models.fields.model_select_field.ModelSelectField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="payroll.item",
                verbose_name="payroll element",
            ),
        ),
        migrations.AlterField(
            model_name="specialemployeeitem",
            name="organization",
            field=core.models.fields.foreignkey.ForeignKey(
                blank=True,
                default=None,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.organization",
                verbose_name="organization",
            ),
        ),
        migrations.AlterField(
            model_name="specialemployeeitem",
            name="updated_at",
            field=core.models.fields.datetimefield.DateTimeField(
                auto_now=True, verbose_name="updated at"
            ),
        ),
        migrations.AlterField(
            model_name="specialemployeeitem",
            name="updated_by",
            field=django_currentuser.db.models.fields.CurrentUserField(
                default=django_currentuser.middleware.get_current_authenticated_user,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                on_update=True,
                related_name="%(app_label)s_%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="updated by",
            ),
        ),
    ]
