# Generated by Django 5.0.4 on 2024-06-04 17:49

import core.models.fields.model_select_to_multiple_field
import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0009_alter_status_options_alter_employee_status"),
        ("payroll", "0005_rename_employee_payslip__employee"),
    ]

    operations = [
        migrations.AddField(
            model_name="payroll",
            name="canvas",
            field=models.FileField(
                blank=True,
                default=None,
                null=True,
                upload_to=core.utils.upload_directory_file,
                verbose_name="canevas",
            ),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="employee_status",
            field=core.models.fields.model_select_to_multiple_field.ModelSelect2Multiple(
                blank=True,
                help_text="laisser vide pour tous",
                to="employee.status",
                verbose_name="état",
            ),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="status",
            field=models.CharField(
                choices=[
                    ("WARNING", "avertissement"),
                    ("PROGRESS", "en cours"),
                    ("SUCCESS", "succès"),
                ],
                default="PROGRESS",
                editable=False,
                max_length=25,
                verbose_name="état",
            ),
        ),
    ]
