# Generated by Django 5.0.4 on 2024-07-10 15:41

import core.models.fields.model_select_field
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0016_branch_category"),
        ("payroll", "0005_remove_employee_payer_name_employee_payer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="payer",
            field=core.models.fields.model_select_field.ModelSelect(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_payer",
                to="employee.payer",
                verbose_name="banque",
            ),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="payroll",
            field=core.models.fields.model_select_field.ModelSelect(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="payroll.payroll",
                verbose_name="paie",
            ),
        ),
    ]
