# Generated by Django 5.0.4 on 2024-09-24 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0005_claim_payrolls_alter_claim_solved"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="is_housed",
            field=models.BooleanField(
                default=False,
                help_text="L'employé est-il logé par l'organisation ?",
                verbose_name="logé",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="mileage_allowance",
            field=models.BooleanField(
                default=0,
                help_text="L'employé bénéficie-t-il de l'indemnité kilométrique ?",
                verbose_name="indemnité kilométrique",
            ),
        ),
    ]
