# Generated by Django 5.0.4 on 2024-06-06 16:51

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0006_payroll_canvas_alter_payroll_employee_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payroll",
            name="addition_items",
            field=models.FileField(
                blank=True,
                default=None,
                null=True,
                upload_to=core.utils.upload_directory_file,
                verbose_name="éléments additionnels",
            ),
        ),
    ]
