# Generated by Django 5.0.4 on 2024-09-24 09:33

import core.models.fields.date_field
import core.models.fields.model_select_field
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0005_alter_direction_options_employee_date_of_leave_and_more"),
        ("payroll", "0006_employee_is_housed_employee_mileage_allowance"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="date_of_leave",
            field=core.models.fields.date_field.DateField(
                default=None, null=True, verbose_name="date de fin de service"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="direction",
            field=core.models.fields.model_select_field.ModelSelect(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_direction",
                to="employee.direction",
                verbose_name="departement",
            ),
        ),
    ]
