# Generated by Django 5.0.4 on 2024-04-26 08:33

import core.models.fields.model_select_to_multiple_field
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0006_salaryadvance"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="payroll",
            name="approvers",
            field=core.models.fields.model_select_to_multiple_field.ModelSelect2Multiple(
                to=settings.AUTH_USER_MODEL, verbose_name="approbateurs"
            ),
        ),
    ]
