# Generated by Django 5.0.4 on 2024-06-06 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0007_payroll_addition_items"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payroll",
            old_name="addition_items",
            new_name="additional_items",
        ),
    ]
