# Generated by Django 5.0.4 on 2024-04-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0007_payroll_approvers"),
    ]

    operations = [
        migrations.AddField(
            model_name="payroll",
            name="approved",
            field=models.BooleanField(default=False, verbose_name="approuvé"),
        ),
    ]
