# Generated by Django 5.0.4 on 2024-05-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0009_specialemployeeitem_delete_salaryadvance"),
    ]

    operations = [
        migrations.AddField(
            model_name="specialemployeeitem",
            name="condition",
            field=models.CharField(
                default="1", max_length=255, verbose_name="condition"
            ),
        ),
    ]
