# Generated by Django 5.0.4 on 2024-07-09 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0011_payslip_emp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payslip",
            name="emp",
        ),
    ]
