# Generated by Django 5.0.4 on 2024-07-09 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0012_remove_payslip_emp"),
    ]

    operations = [
        migrations.AddField(
            model_name="payslip",
            name="employee",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="payroll.employee",
                verbose_name="employé",
            ),
        ),
    ]
