# Generated by Django 5.0.4 on 2024-07-10 12:58

import core.models.fields.model_select_field
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0013_payslip_employee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itempaid",
            name="payslip",
            field=core.models.fields.model_select_field.ModelSelect(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="payroll.payslip",
                verbose_name="fiche de paie",
            ),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="employee",
            field=core.models.fields.model_select_field.ModelSelect(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="payroll.employee",
                verbose_name="employé",
            ),
        ),
    ]
