# Generated by Django 5.0.4 on 2024-10-25 08:53

import core.models.fields.json_field
import core.models.fields.model_select_field
import core.models.fields.time_field
import datetime
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("employee", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LabourRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "approved",
                    models.BooleanField(
                        default=False, editable=False, verbose_name="approuvé"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="mis à jour le/à"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le/à"),
                ),
                (
                    "metadata",
                    core.models.fields.json_field.JSONField(
                        blank=True, default=dict, verbose_name="meta"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="créé par",
                    ),
                ),
                (
                    "employee",
                    core.models.fields.model_select_field.ModelSelect(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employee.employee",
                        verbose_name="employé",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.organization",
                        verbose_name="organisation",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        on_update=True,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="mis à jour par",
                    ),
                ),
            ],
            options={
                "verbose_name": "demande de main-d'œuvre",
                "verbose_name_plural": "demande de main-d'œuvre",
            },
        ),
        migrations.CreateModel(
            name="Labour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "approved",
                    models.BooleanField(
                        default=False, editable=False, verbose_name="approuvé"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="mis à jour le/à"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le/à"),
                ),
                (
                    "metadata",
                    core.models.fields.json_field.JSONField(
                        blank=True, default=dict, verbose_name="meta"
                    ),
                ),
                (
                    "designation",
                    models.CharField(
                        default=None,
                        max_length=250,
                        null=True,
                        verbose_name="désignation",
                    ),
                ),
                ("quantity", models.FloatField(default=0.0, verbose_name="quantité")),
                (
                    "provenance",
                    models.CharField(
                        default=None,
                        max_length=250,
                        null=True,
                        verbose_name="provenance",
                    ),
                ),
                (
                    "destination",
                    models.CharField(
                        default=None,
                        max_length=250,
                        null=True,
                        verbose_name="destination",
                    ),
                ),
                (
                    "observation",
                    models.CharField(
                        default=None,
                        max_length=250,
                        null=True,
                        verbose_name="observation",
                    ),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="créé par",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.organization",
                        verbose_name="organisation",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        on_update=True,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="mis à jour par",
                    ),
                ),
                (
                    "labourrequest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="logistic.labourrequest",
                        verbose_name="demande de main-d'œuvre #",
                    ),
                ),
            ],
            options={
                "verbose_name": "labour",
                "verbose_name_plural": "labours",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "approved",
                    models.BooleanField(
                        default=False, editable=False, verbose_name="approuvé"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="mis à jour le/à"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le/à"),
                ),
                (
                    "metadata",
                    core.models.fields.json_field.JSONField(
                        blank=True, default=dict, verbose_name="meta"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="nom")),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="créé par",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.organization",
                        verbose_name="organisation",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        on_update=True,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="mis à jour par",
                    ),
                ),
            ],
            options={
                "verbose_name": "produit",
                "verbose_name_plural": "produits",
            },
        ),
        migrations.CreateModel(
            name="ProductRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "approved",
                    models.BooleanField(
                        default=False, editable=False, verbose_name="approuvé"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="mis à jour le/à"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le/à"),
                ),
                (
                    "metadata",
                    core.models.fields.json_field.JSONField(
                        blank=True, default=dict, verbose_name="meta"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="créé par",
                    ),
                ),
                (
                    "employee",
                    core.models.fields.model_select_field.ModelSelect(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employee.employee",
                        verbose_name="employé",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.organization",
                        verbose_name="organisation",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        on_update=True,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="mis à jour par",
                    ),
                ),
            ],
            options={
                "verbose_name": "demande de produit",
                "verbose_name_plural": "demandes de produits",
            },
        ),
        migrations.CreateModel(
            name="ProductQuantity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "approved",
                    models.BooleanField(
                        default=False, editable=False, verbose_name="approuvé"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="mis à jour le/à"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le/à"),
                ),
                (
                    "metadata",
                    core.models.fields.json_field.JSONField(
                        blank=True, default=dict, verbose_name="meta"
                    ),
                ),
                (
                    "requested_quantity",
                    models.FloatField(default=0.0, verbose_name="quantité demandée"),
                ),
                (
                    "delivered_quantity",
                    models.FloatField(default=0.0, verbose_name="quantité livrée"),
                ),
                (
                    "observation",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="observation"
                    ),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="créé par",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.organization",
                        verbose_name="organisation",
                    ),
                ),
                (
                    "product",
                    core.models.fields.model_select_field.ModelSelect(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="logistic.product",
                        verbose_name="produit",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        on_update=True,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="mis à jour par",
                    ),
                ),
                (
                    "productrequest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="logistic.productrequest",
                        verbose_name="demande de produit #",
                    ),
                ),
            ],
            options={
                "verbose_name": "quantité de produits",
                "verbose_name_plural": "quantités de produits",
            },
        ),
        migrations.CreateModel(
            name="VehicleRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "approved",
                    models.BooleanField(
                        default=False, editable=False, verbose_name="approuvé"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="mis à jour le/à"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le/à"),
                ),
                (
                    "metadata",
                    core.models.fields.json_field.JSONField(
                        blank=True, default=dict, verbose_name="meta"
                    ),
                ),
                ("reason", models.TextField(blank=True, verbose_name="raison")),
                (
                    "destination",
                    models.CharField(
                        default=None,
                        max_length=250,
                        null=True,
                        verbose_name="destination",
                    ),
                ),
                (
                    "leaving_time",
                    core.models.fields.time_field.TimeField(
                        default=datetime.datetime.today, verbose_name="heure de départ"
                    ),
                ),
                (
                    "type_of_vehicle",
                    models.CharField(
                        default=None,
                        max_length=250,
                        null=True,
                        verbose_name="type de véhicule",
                    ),
                ),
                (
                    "driver_name",
                    models.CharField(
                        default=None,
                        max_length=250,
                        null=True,
                        verbose_name="nom du conducteur",
                    ),
                ),
                (
                    "vehicle_licence_plate",
                    models.CharField(
                        default=None,
                        max_length=250,
                        null=True,
                        verbose_name="plaque d'immatriculation du véhicule",
                    ),
                ),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="créé par",
                    ),
                ),
                (
                    "employee",
                    core.models.fields.model_select_field.ModelSelect(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employee.employee",
                        verbose_name="employé",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.organization",
                        verbose_name="organisation",
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        on_update=True,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="mis à jour par",
                    ),
                ),
            ],
            options={
                "verbose_name": "demande de véhicule",
                "verbose_name_plural": "demandes de véhicules",
            },
        ),
    ]
